//FLASH
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
//USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
//PRODUCTS
export const SET_PRODUCTS = 'SET_PRODUCTS';
//SHOPPING CART
export const ADD_TO_CART = 'ADD_TO_CART';
//PROFILE
export const SET_PROFILE = 'SET_PROFILE';