// FLASH
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
// USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// PRODUCTS
export const SET_PRODUCTS = 'SET_PRODUCTS';
// SHOPPING CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_CART = 'SET_CART';
export const DELETE_CART = 'DELETE_CART';
// PROFILE
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const QUANTITY_DECREMENT = 'QUANTITY_DECREMENT';
export const QUANTITY_INCREMENT = 'QUANTITY_INCREMENT';
export const FETCH_AVATAR = 'FETCH_AVATAR';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const DELETE_ORDERS = 'DELETE_ORDERS';

export const LOAD = 'LOAD';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const FETCHING_CART = 'FETCHING_CART';
export const FETCHING_CART_SUCCESS = 'FETCHING_CART_SUCCESS';
export const FETCHING_CART_FAILURE = 'FETCHING_CART_FAILURE';

